
package  com.gzyct.m.api.busi.wsdl.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MobsetApiSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MobsetApiSoap {


    /**
     * ���Ͷ���
     * 
     * @param timeStamp
     * @param addNum
     * @param timer
     * @param mobileList
     * @param password
     * @param corpID
     * @param longSms
     * @param loginName
     * @param count
     * @param errMsg
     * @param smsIDList
     * @param content
     */
    @WebMethod(operationName = "Sms_Send", action = "http://tempuri.org/Sms_Send")
    @RequestWrapper(localName = "Sms_Send", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.SmsSend")
    @ResponseWrapper(localName = "Sms_SendResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.SmsSendResponse")
    public void smsSend(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "AddNum", targetNamespace = "http://tempuri.org/")
        String addNum,
        @WebParam(name = "Timer", targetNamespace = "http://tempuri.org/")
        String timer,
        @WebParam(name = "LongSms", targetNamespace = "http://tempuri.org/")
        long longSms,
        @WebParam(name = "MobileList", targetNamespace = "http://tempuri.org/")
        ArrayOfMobileList mobileList,
        @WebParam(name = "Content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "Count", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> count,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg,
        @WebParam(name = "SmsIDList", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfSmsIDList> smsIDList);

    /**
     * ȡ���ж���
     * 
     * @param timeStamp
     * @param password
     * @param corpID
     * @param loginName
     * @param count
     * @param errMsg
     * @param smsRecvList
     */
    @WebMethod(operationName = "Sms_GetRecv", action = "http://tempuri.org/Sms_GetRecv")
    @RequestWrapper(localName = "Sms_GetRecv", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.SmsGetRecv")
    @ResponseWrapper(localName = "Sms_GetRecvResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.SmsGetRecvResponse")
    public void smsGetRecv(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "Count", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> count,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg,
        @WebParam(name = "SmsRecvList", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfSmsRecvList> smsRecvList);

    /**
     * ȡ����״̬����
     * 
     * @param timeStamp
     * @param password
     * @param smsReportList
     * @param corpID
     * @param loginName
     * @param count
     * @param errMsg
     */
    @WebMethod(operationName = "Sms_GetReport", action = "http://tempuri.org/Sms_GetReport")
    @RequestWrapper(localName = "Sms_GetReport", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.SmsGetReport")
    @ResponseWrapper(localName = "Sms_GetReportResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.SmsGetReportResponse")
    public void smsGetReport(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "Count", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> count,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg,
        @WebParam(name = "SmsReportList", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfSmsReportList> smsReportList);

    /**
     * ȡ����ǩ��
     * 
     * @param timeStamp
     * @param password
     * @param corpID
     * @param errCode
     * @param loginName
     * @param errMsg
     * @param sign
     */
    @WebMethod(operationName = "Sms_GetSign", action = "http://tempuri.org/Sms_GetSign")
    @RequestWrapper(localName = "Sms_GetSign", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.SmsGetSign")
    @ResponseWrapper(localName = "Sms_GetSignResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.SmsGetSignResponse")
    public void smsGetSign(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "ErrCode", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> errCode,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg,
        @WebParam(name = "Sign", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> sign);

    /**
     * ȡ���ſ������
     * 
     * @param timeStamp
     * @param password
     * @param corpID
     * @param balance
     * @param loginName
     * @param errMsg
     */
    @WebMethod(operationName = "Sms_GetBalance", action = "http://tempuri.org/Sms_GetBalance")
    @RequestWrapper(localName = "Sms_GetBalance", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.SmsGetBalance")
    @ResponseWrapper(localName = "Sms_GetBalanceResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.SmsGetBalanceResponse")
    public void smsGetBalance(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "Balance", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> balance,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg);

    /**
     * �ϴ������ļ�
     * 
     * @param timeStamp
     * @param password
     * @param smilType
     * @param corpID
     * @param subject
     * @param loginName
     * @param mmsFileID
     * @param errMsg
     * @param mmsFileList
     */
    @WebMethod(operationName = "Mms_UpFile", action = "http://tempuri.org/Mms_UpFile")
    @RequestWrapper(localName = "Mms_UpFile", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.MmsUpFile")
    @ResponseWrapper(localName = "Mms_UpFileResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.MmsUpFileResponse")
    public void mmsUpFile(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "Subject", targetNamespace = "http://tempuri.org/")
        String subject,
        @WebParam(name = "SmilType", targetNamespace = "http://tempuri.org/")
        long smilType,
        @WebParam(name = "MmsFileList", targetNamespace = "http://tempuri.org/")
        ArrayOfMmsFileGroup mmsFileList,
        @WebParam(name = "MmsFileID", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> mmsFileID,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg);

    /**
     * ��ѯ�����ļ�״̬
     * 
     * @param timeStamp
     * @param password
     * @param corpID
     * @param size
     * @param createTime
     * @param loginName
     * @param mmsFileID
     * @param errMsg
     * @param title
     * @param status
     */
    @WebMethod(operationName = "Mms_GetFileStatus", action = "http://tempuri.org/Mms_GetFileStatus")
    @RequestWrapper(localName = "Mms_GetFileStatus", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.MmsGetFileStatus")
    @ResponseWrapper(localName = "Mms_GetFileStatusResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.MmsGetFileStatusResponse")
    public void mmsGetFileStatus(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "MmsFileID", targetNamespace = "http://tempuri.org/")
        long mmsFileID,
        @WebParam(name = "Status", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> status,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg,
        @WebParam(name = "Title", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> title,
        @WebParam(name = "Size", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> size,
        @WebParam(name = "CreateTime", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> createTime);

    /**
     * ���Ͳ���
     * 
     * @param timeStamp
     * @param addNum
     * @param timer
     * @param mobileList
     * @param password
     * @param corpID
     * @param loginName
     * @param mmsFileID
     * @param count
     * @param errMsg
     * @param mmsIDList
     */
    @WebMethod(operationName = "Mms_Send", action = "http://tempuri.org/Mms_Send")
    @RequestWrapper(localName = "Mms_Send", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.MmsSend")
    @ResponseWrapper(localName = "Mms_SendResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.MmsSendResponse")
    public void mmsSend(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "AddNum", targetNamespace = "http://tempuri.org/")
        String addNum,
        @WebParam(name = "Timer", targetNamespace = "http://tempuri.org/")
        String timer,
        @WebParam(name = "MobileList", targetNamespace = "http://tempuri.org/")
        ArrayOfMobileList mobileList,
        @WebParam(name = "MmsFileID", targetNamespace = "http://tempuri.org/")
        long mmsFileID,
        @WebParam(name = "Count", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> count,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg,
        @WebParam(name = "MmsIDList", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfMmsIDList> mmsIDList);

    /**
     * ȡ����״̬
     * 
     * @param timeStamp
     * @param password
     * @param mmsReportList
     * @param corpID
     * @param loginName
     * @param count
     * @param errMsg
     */
    @WebMethod(operationName = "Mms_GetReport", action = "http://tempuri.org/Mms_GetReport")
    @RequestWrapper(localName = "Mms_GetReport", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.MmsGetReport")
    @ResponseWrapper(localName = "Mms_GetReportResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.MmsGetReportResponse")
    public void mmsGetReport(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "Count", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> count,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg,
        @WebParam(name = "MmsReportList", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfMmsReportList> mmsReportList);

    /**
     * ȡ��������
     * 
     * @param timeStamp
     * @param addNum
     * @param password
     * @param recvTime
     * @param corpID
     * @param subject
     * @param loginName
     * @param count
     * @param errMsg
     * @param mobile
     * @param recvNum
     * @param mmsRecvFileList
     */
    @WebMethod(operationName = "Mms_GetRecv", action = "http://tempuri.org/Mms_GetRecv")
    @RequestWrapper(localName = "Mms_GetRecv", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.MmsGetRecv")
    @ResponseWrapper(localName = "Mms_GetRecvResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.MmsGetRecvResponse")
    public void mmsGetRecv(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "Count", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> count,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> mobile,
        @WebParam(name = "RecvNum", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> recvNum,
        @WebParam(name = "AddNum", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> addNum,
        @WebParam(name = "Subject", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> subject,
        @WebParam(name = "RecvTime", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> recvTime,
        @WebParam(name = "MmsRecvFileList", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfMmsRecvFileGroup> mmsRecvFileList);

    /**
     * �ϴ������ļ�
     * 
     * @param timeStamp
     * @param password
     * @param corpID
     * @param subject
     * @param loginName
     * @param fileData
     * @param autoDelete
     * @param taskFileID
     * @param errMsg
     */
    @WebMethod(operationName = "Task_UpFile", action = "http://tempuri.org/Task_UpFile")
    @RequestWrapper(localName = "Task_UpFile", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskUpFile")
    @ResponseWrapper(localName = "Task_UpFileResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskUpFileResponse")
    public void taskUpFile(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "Subject", targetNamespace = "http://tempuri.org/")
        String subject,
        @WebParam(name = "AutoDelete", targetNamespace = "http://tempuri.org/")
        long autoDelete,
        @WebParam(name = "FileData", targetNamespace = "http://tempuri.org/")
        byte[] fileData,
        @WebParam(name = "TaskFileID", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> taskFileID,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg);

    /**
     * ɾ�������ļ�
     * 
     * @param timeStamp
     * @param password
     * @param corpID
     * @param errCode
     * @param loginName
     * @param taskFileID
     * @param errMsg
     */
    @WebMethod(operationName = "Task_DelFile", action = "http://tempuri.org/Task_DelFile")
    @RequestWrapper(localName = "Task_DelFile", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskDelFile")
    @ResponseWrapper(localName = "Task_DelFileResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskDelFileResponse")
    public void taskDelFile(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "TaskFileID", targetNamespace = "http://tempuri.org/")
        long taskFileID,
        @WebParam(name = "ErrCode", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> errCode,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg);

    /**
     * �ύ��������
     * 
     * @param timeStamp
     * @param atTime
     * @param mobileList
     * @param password
     * @param taskSmsID
     * @param corpID
     * @param longSms
     * @param loginName
     * @param errMsg
     * @param priority
     * @param content
     */
    @WebMethod(operationName = "Task_SmsSend", action = "http://tempuri.org/Task_SmsSend")
    @RequestWrapper(localName = "Task_SmsSend", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskSmsSend")
    @ResponseWrapper(localName = "Task_SmsSendResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskSmsSendResponse")
    public void taskSmsSend(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "Content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "LongSms", targetNamespace = "http://tempuri.org/")
        long longSms,
        @WebParam(name = "Priority", targetNamespace = "http://tempuri.org/")
        long priority,
        @WebParam(name = "AtTime", targetNamespace = "http://tempuri.org/")
        String atTime,
        @WebParam(name = "MobileList", targetNamespace = "http://tempuri.org/")
        ArrayOfMobileFileGroup mobileList,
        @WebParam(name = "TaskSmsID", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> taskSmsID,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg);

    /**
     * ȡ��������״̬
     * 
     * @param timeStamp
     * @param password
     * @param taskSmsID
     * @param corpID
     * @param yfMobileCount
     * @param loginName
     * @param errMsg
     * @param mobileCount
     * @param beginTime
     * @param endTime
     * @param status
     */
    @WebMethod(operationName = "Task_GetSmsStatus", action = "http://tempuri.org/Task_GetSmsStatus")
    @RequestWrapper(localName = "Task_GetSmsStatus", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskGetSmsStatus")
    @ResponseWrapper(localName = "Task_GetSmsStatusResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskGetSmsStatusResponse")
    public void taskGetSmsStatus(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "TaskSmsID", targetNamespace = "http://tempuri.org/")
        long taskSmsID,
        @WebParam(name = "Status", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> status,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg,
        @WebParam(name = "MobileCount", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> mobileCount,
        @WebParam(name = "YFMobileCount", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> yfMobileCount,
        @WebParam(name = "BeginTime", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> beginTime,
        @WebParam(name = "EndTime", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> endTime);

    /**
     * ֹͣ��������
     * 
     * @param timeStamp
     * @param password
     * @param taskSmsID
     * @param corpID
     * @param errCode
     * @param loginName
     * @param errMsg
     */
    @WebMethod(operationName = "Task_SmsStop", action = "http://tempuri.org/Task_SmsStop")
    @RequestWrapper(localName = "Task_SmsStop", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskSmsStop")
    @ResponseWrapper(localName = "Task_SmsStopResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskSmsStopResponse")
    public void taskSmsStop(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "TaskSmsID", targetNamespace = "http://tempuri.org/")
        long taskSmsID,
        @WebParam(name = "ErrCode", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> errCode,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg);

    /**
     * ������������
     * 
     * @param timeStamp
     * @param password
     * @param taskSmsID
     * @param corpID
     * @param errCode
     * @param loginName
     * @param errMsg
     */
    @WebMethod(operationName = "Task_SmsStart", action = "http://tempuri.org/Task_SmsStart")
    @RequestWrapper(localName = "Task_SmsStart", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskSmsStart")
    @ResponseWrapper(localName = "Task_SmsStartResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskSmsStartResponse")
    public void taskSmsStart(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "TaskSmsID", targetNamespace = "http://tempuri.org/")
        long taskSmsID,
        @WebParam(name = "ErrCode", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> errCode,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg);

    /**
     * �ύ��������
     * 
     * @param timeStamp
     * @param atTime
     * @param mobileList
     * @param password
     * @param corpID
     * @param loginName
     * @param mmsFileID
     * @param errMsg
     * @param priority
     * @param taskMmsID
     */
    @WebMethod(operationName = "Task_MmsSend", action = "http://tempuri.org/Task_MmsSend")
    @RequestWrapper(localName = "Task_MmsSend", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskMmsSend")
    @ResponseWrapper(localName = "Task_MmsSendResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskMmsSendResponse")
    public void taskMmsSend(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "MmsFileID", targetNamespace = "http://tempuri.org/")
        long mmsFileID,
        @WebParam(name = "Priority", targetNamespace = "http://tempuri.org/")
        long priority,
        @WebParam(name = "AtTime", targetNamespace = "http://tempuri.org/")
        String atTime,
        @WebParam(name = "MobileList", targetNamespace = "http://tempuri.org/")
        ArrayOfMobileFileGroup mobileList,
        @WebParam(name = "TaskMmsID", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> taskMmsID,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg);

    /**
     * ȡ��������״̬
     * 
     * @param timeStamp
     * @param password
     * @param corpID
     * @param yfMobileCount
     * @param loginName
     * @param errMsg
     * @param mobileCount
     * @param beginTime
     * @param endTime
     * @param taskMmsID
     * @param status
     */
    @WebMethod(operationName = "Task_GetMmsStatus", action = "http://tempuri.org/Task_GetMmsStatus")
    @RequestWrapper(localName = "Task_GetMmsStatus", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskGetMmsStatus")
    @ResponseWrapper(localName = "Task_GetMmsStatusResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskGetMmsStatusResponse")
    public void taskGetMmsStatus(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "TaskMmsID", targetNamespace = "http://tempuri.org/")
        long taskMmsID,
        @WebParam(name = "Status", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> status,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg,
        @WebParam(name = "MobileCount", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> mobileCount,
        @WebParam(name = "YFMobileCount", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> yfMobileCount,
        @WebParam(name = "BeginTime", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> beginTime,
        @WebParam(name = "EndTime", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> endTime);

    /**
     * ֹͣ��������
     * 
     * @param timeStamp
     * @param password
     * @param corpID
     * @param errCode
     * @param loginName
     * @param errMsg
     * @param taskMmsID
     */
    @WebMethod(operationName = "Task_MmsStop", action = "http://tempuri.org/Task_MmsStop")
    @RequestWrapper(localName = "Task_MmsStop", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskMmsStop")
    @ResponseWrapper(localName = "Task_MmsStopResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskMmsStopResponse")
    public void taskMmsStop(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "TaskMmsID", targetNamespace = "http://tempuri.org/")
        long taskMmsID,
        @WebParam(name = "ErrCode", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> errCode,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg);

    /**
     * ������������
     * 
     * @param timeStamp
     * @param password
     * @param corpID
     * @param errCode
     * @param loginName
     * @param errMsg
     * @param taskMmsID
     */
    @WebMethod(operationName = "Task_MmsStart", action = "http://tempuri.org/Task_MmsStart")
    @RequestWrapper(localName = "Task_MmsStart", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskMmsStart")
    @ResponseWrapper(localName = "Task_MmsStartResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.TaskMmsStartResponse")
    public void taskMmsStart(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "TaskMmsID", targetNamespace = "http://tempuri.org/")
        long taskMmsID,
        @WebParam(name = "ErrCode", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> errCode,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg);

    /**
     * ������ȡ�������
     * 
     * @param timeStamp
     * @param agentID
     * @param password
     * @param balance
     * @param loginName
     * @param errMsg
     */
    @WebMethod(operationName = "Agent_GetSmsBalance", action = "http://tempuri.org/Agent_GetSmsBalance")
    @RequestWrapper(localName = "Agent_GetSmsBalance", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.AgentGetSmsBalance")
    @ResponseWrapper(localName = "Agent_GetSmsBalanceResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.AgentGetSmsBalanceResponse")
    public void agentGetSmsBalance(
        @WebParam(name = "AgentID", targetNamespace = "http://tempuri.org/")
        long agentID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "Balance", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> balance,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg);

    /**
     * ������ȡ������ҵ�Ķ������
     * 
     * @param timeStamp
     * @param agentID
     * @param password
     * @param corpID
     * @param balance
     * @param loginName
     * @param errMsg
     */
    @WebMethod(operationName = "Agent_GetCorpSmsBalance", action = "http://tempuri.org/Agent_GetCorpSmsBalance")
    @RequestWrapper(localName = "Agent_GetCorpSmsBalance", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.AgentGetCorpSmsBalance")
    @ResponseWrapper(localName = "Agent_GetCorpSmsBalanceResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.AgentGetCorpSmsBalanceResponse")
    public void agentGetCorpSmsBalance(
        @WebParam(name = "AgentID", targetNamespace = "http://tempuri.org/")
        long agentID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "Balance", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> balance,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg);

    /**
     * ������Ϊ������ҵ��ֵ����
     * 
     * @param timeStamp
     * @param agentID
     * @param password
     * @param payMoney
     * @param corpID
     * @param balance
     * @param payMode
     * @param payPrice
     * @param loginName
     * @param errMsg
     * @param payPresent
     * @param payMemo
     */
    @WebMethod(operationName = "Agent_CorpSmsPay", action = "http://tempuri.org/Agent_CorpSmsPay")
    @RequestWrapper(localName = "Agent_CorpSmsPay", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.AgentCorpSmsPay")
    @ResponseWrapper(localName = "Agent_CorpSmsPayResponse", targetNamespace = "http://tempuri.org/", className = " com.gzyct.m.api.busi.wsdl.sms.AgentCorpSmsPayResponse")
    public void agentCorpSmsPay(
        @WebParam(name = "AgentID", targetNamespace = "http://tempuri.org/")
        long agentID,
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp,
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        long corpID,
        @WebParam(name = "PayMode", targetNamespace = "http://tempuri.org/")
        String payMode,
        @WebParam(name = "PayMoney", targetNamespace = "http://tempuri.org/")
        double payMoney,
        @WebParam(name = "PayPrice", targetNamespace = "http://tempuri.org/")
        double payPrice,
        @WebParam(name = "PayPresent", targetNamespace = "http://tempuri.org/")
        long payPresent,
        @WebParam(name = "PayMemo", targetNamespace = "http://tempuri.org/")
        String payMemo,
        @WebParam(name = "Balance", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Long> balance,
        @WebParam(name = "ErrMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> errMsg);

}
